(* ::Package:: *)

(* ::Input:: *)
(*(*number to momentum*)*)
(*momm[binary_]:=Sum[mom[[-i]]IntegerDigits[binary,2,Length[flv]][[i]],{i,1,Length[flv]}];*)
(**)
(**)
(*(*algebra of 4 vector*)*)
(*Sp[a_List,b_List]:=a.gmunu.b (*4d Scalar Product*)*)
(*sum[one_]:=Sum[i,{i,Flatten[{one}]}]*)
(*p[one_,two_]:=momm[sum[one]+sum[two]]*)
(*bit[one_,two_]:=BitAnd[sum[one],sum[two]]*)
(**)
(**)
