(* ::Package:: *)

(* ::Input:: *)
(*(*All about matrices*)*)
(*GammaMat[index_]:=If[index!= 0,ArrayFlatten[{{0,PauliMatrix[index]},{-PauliMatrix[index],0}}],ArrayFlatten[{{0,-PauliMatrix[index]},{-PauliMatrix[index],0}}]]*)
(*Gammafive=I Apply[Dot,Table[GammaMat[i],{i,0,3}]];*)
(*rightpro=1/2(IdentityMatrix[4]+Gammafive);*)
(*leftpro=1/2(IdentityMatrix[4]-Gammafive);*)
(*gmunu=DiagonalMatrix[{1,-1,-1,-1},0,4];*)
(*identity=IdentityMatrix[4];*)
(*cov[fourv_]:=Array[fourv,4,0]*)
(*contv[fourv_]:=gmunu.fourv*)
(*LC[fourv_]:={fourv[[1]]+fourv[[4]],fourv[[1]]-fourv[[4]],fourv[[2]]+Simplify[I fourv[[3]]],fourv[[2]]-Simplify[I fourv[[3]]]}*)
(*LCI[fourv_]:={ 1/2(fourv[[1]]+fourv[[2]]), 1/2(fourv[[3]]+fourv[[4]]),1/(2I)(fourv[[3]]-fourv[[4]]),1/2(fourv[[1]]-fourv[[2]])}*)
(*slash[fourv_]:=Sum[contv[fourv][[i+1]] GammaMat[i],{i,0,3}]*)
(**)
(*(*Initial conditions*)*)
(*(* massless spinor (mass spinor<<energy of the spinors)*)*)
(**)
(*uR[p_]:=Which[LC[p][[1]]!= 0,{Sqrt[LC[p][[1]]],(LC[p][[3]])/Sqrt[LC[p][[1]]],0,0},LC[p][[1]]==0,{0,-Sqrt[LC[p][[2]]],0,0}]//Chop*)
(*ubarR[p_]:=Which[LC[p][[1]]!= 0,{0,0,-Sqrt[LC[p][[1]]],-(LC[p][[4]])/Sqrt[LC[p][[1]]]},LC[p][[1]]==0,{0,0,0,Sqrt[LC[p][[2]]]}]//Chop*)
(*uL[p_]:=Which[LC[p][[1]]!= 0,{0,0,-(LC[p][[4]])/Sqrt[LC[p][[1]]],Sqrt[LC[p][[1]]]},LC[p][[1]]==0,{0,0,Sqrt[LC[p][[2]]],0}]//Chop*)
(*ubarL[p_]:=Which[LC[p][[1]]!= 0,{(LC[p][[3]])/Sqrt[LC[p][[1]]],-Sqrt[LC[p][[1]]],0,0},LC[p][[1]]==0,{-Sqrt[LC[p][[2]]],0,0,0}]//Chop*)
(**)
(**)
(*(*massive spinors *)*)
(*norm[p_]:=Norm[{p[[2]],p[[3]],p[[4]]}] (*3d vector length*)*)
(*a[p_]:=p[[1]]+norm[p]  *)
(*b[p_]:=p[[4]]+norm[p]*)
(*c[p_]:=2norm[p]*)
(*r[p_]:=Sqrt[a[p] b[p] c[p]]*)
(*uplus[p_]:={r[p]/c[p],a[p](LC[p][[3]])/r[p],-m b[p]/r[p],-m(LC[p][[3]])/r[p]}//Chop*)
(*ubarplus[p_]:={m b[p]/r[p],m (LC[p][[4]])/r[p],-r[p]/c[p],-a[p](LC[p][[4]])/r[p]}//Chop*)
(*uminus[p_]:={m (LC[p][[4]])/r[p],-m b[p]/r[p],-a[p](LC[p][[4]])/r[p],r[p]/c[p]}//Chop*)
(*ubarminus[p_]:={a[p](LC[p][[3]])/r[p],-r[p]/c[p],-m(LC[p][[3]])/r[p],m b[p]/r[p]}//Chop*)
(**)
(*vplus[p_]:={-m(LC[p][[4]])/r[p],m b[p]/r[p],-a[p](LC[p][[4]])/r[p],r[p]/c[p]}//Chop*)
(*vbarplus[p_]:={a[p](LC[p][[3]])/r[p],-r[p]/c[p],m (LC[p][[3]])/r[p],-m b[p]/r[p]}//Chop*)
(*vminus[p_]:={r[p]/c[p],a (LC[p][[3]])/r[p],m b[p]/r[p],m (LC[p][[3]])/r[p]}//Chop*)
(*vbarminus[p_]:={-m b[p]/r[p],-m(LC[p][[4]])/r[p],-r[p]/c[p],-a(LC[p][[4]])/r[p]}//Chop*)
(**)
(**)
(*(*polarization vectors of boson (photon)*)*)
(*pT[p_]:=Norm[{p[[2]],p[[3]]}]*)
(*\[Epsilon]minusVA[p_]:={-pT[p]/(Sqrt[2]norm[p]),pT[p]/(Sqrt[2]norm[p]),(LC[p][[3]])(norm[p]+p[[4]])/(Sqrt[2]norm[p]pT[p]),(LC[p][[4]])(-norm[p]+p[[4]])/(Sqrt[2]norm[p]pT[p])}*)
(*\[Epsilon]plusVA[p_]:={pT[p]/(Sqrt[2]norm[p]),-pT[p]/(Sqrt[2]norm[p]),(LC[p][[3]])(norm[p]-p[[4]])/(Sqrt[2]norm[p]pT[p]),(LC[p][[4]])(-norm[p]-p[[4]])/(Sqrt[2]norm[p]pT[p])}*)
(*\[Epsilon]nullVA[p_]:={(norm[p]/Sqrt[Sp[p,p]])+(p[[4]]p[[1]]/(norm[p]Sqrt[Sp[p,p]])),(norm[p]/Sqrt[Sp[p,p]])-(p[[4]]p[[1]]/(norm[p]Sqrt[Sp[p,p]])),((LC[p][[3]])p[[1]])/(norm[p]Sqrt[Sp[p,p]]),((LC[p][[4]])p[[1]])/(norm[p]Sqrt[Sp[p,p]])}*)
(*(*\[Epsilon]minusVAstar[p_]:={-pT[p]/(Sqrt[2]norm[p]),pT[p]/(Sqrt[2]norm[p]),(LC[p][[4]])(norm[p]+p[[4]])/(Sqrt[2]norm[p]pT[p]),(LC[p][[3]])(-norm[p]+p[[4]])/(Sqrt[2]norm[p]pT[p])}*)
(*\[Epsilon]plusVAstar[p_]:={pT[p]/(Sqrt[2]norm[p]),-pT[p]/(Sqrt[2]norm[p]),(LC[p][[4]])(norm[p]-p[[4]])/(Sqrt[2]norm[p]pT[p]),(LC[p][[3]])(-norm[p]-p[[4]])/(Sqrt[2]norm[p]pT[p])}*)*)
(**)
