(* ::Package:: *)

(* ::Input:: *)
(*(*Important Functions*)*)
(*pol[p_,j_,i_]:=Which[m==0,*)
(*Which[i<= numinput,Which[checktype[[i]]==0&&polsign[[j,i]]==1,\[Epsilon]plusVA[p],checktype[[i]]==0&&polsign[[j,i]]==2,\[Epsilon]minusVA[p],checktype[[i]]==1&&polsign[[j,i]]==1,uR[p],checktype[[i]]==1&&polsign[[j,i]]==2,uL[p],checktype[[i]]==-1&&polsign[[j,i]]==1,ubarR[p],checktype[[i]]==-1&&polsign[[j,i]]==2,ubarL[p]*)
(*],*)
(*i>numinput,Which[checktype[[i]]==0&&polsign[[j,i]]==1,\[Epsilon]plusVA[p],checktype[[i]]==0&&polsign[[j,i]]==2,\[Epsilon]minusVA[p],checktype[[i]]==-1&&polsign[[j,i]]==1,ubarR[p],checktype[[i]]==-1&&polsign[[j,i]]==2,ubarL[p],checktype[[i]]==1&&polsign[[j,i]]==1,uR[p],checktype[[i]]==1&&polsign[[j,i]]==2,uL[p]*)
(*]*)
(*],*)
(*m!= 0,*)
(*Which[i<= numinput,Which[checktype[[i]]==0&&polsign[[j,i]]==1,\[Epsilon]plusVA[p],checktype[[i]]==0&&polsign[[j,i]]==2,\[Epsilon]minusVA[p],checktype[[i]]==1&&polsign[[j,i]]==1,uplus[p],checktype[[i]]==1&&polsign[[j,i]]==2,uminus[p],checktype[[i]]==-1&&polsign[[j,i]]==1,vbarplus[p],checktype[[i]]==-1&&polsign[[j,i]]==2,vbarminus[p]*)
(*],*)
(*i>numinput,Which[checktype[[i]]==0&&polsign[[j,i]]==1,\[Epsilon]plusVA[p],checktype[[i]]==0&&polsign[[j,i]]==2,\[Epsilon]minusVA[p],checktype[[i]]==-1&&polsign[[j,i]]==1,ubarplus[p],checktype[[i]]==-1&&polsign[[j,i]]==2,ubarminus[p],checktype[[i]]==1&&polsign[[j,i]]==1,vplus[p],checktype[[i]]==1&&polsign[[j,i]]==2,vminus[p]*)
(*]*)
(*]*)
(*]*)
